version: '3'
services:
  react-app:
    build: ./client # Path to your react app Dockerfile
    stdin_open: true
    ports:
      - "3001:3000" # Change the host port to 3001
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
